script: "bundle exec rake test"
bundler_args: "--no-deployment"
cache: bundler
sudo: false
branches:
  only: master
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
